spring.datasource.url=jdbc:postgresql://localhost:5432/stock_portfolio
spring.datasource.username=user
spring.datasource.password=password

# Aceasta linie creeaza automat tabelele în Postgres pe baza claselor Java
spring.jpa.hibernate.ddl-auto=update
# Asta iti arata în consola comenzile SQL pe care le face Spring sub capota
spring.jpa.show-sql=true    